name: docs

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get Tag
      id: get_tag
      run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
    - name: Run Jazzy
      uses: swiftpackages/publish-jazzy-docs@v1.1.3
      with:
        args: --module_version $tag --github_file_prefix https://github.com/swiftpackages/Heap/tree/$tag --output docs/$tag
        config: .jazzy.yaml
        personal_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
